# Generated by Selenium IDE
import pytest
import time
import sys
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:8080/login.html")
    self.driver.set_window_size(1533, 1011)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Gabriel")
    self.driver.find_element(By.ID, "password").send_keys("Gabriel")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.save_screenshot(f'{sys._getframe().f_code.co_name}.png') # generates a png file with the name
