# Generated by Selenium IDE
import pytest
import time
import json
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logout(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1533, 1013)
    self.driver.find_element(By.LINK_TEXT, "Accedi").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Nicolas")
    self.driver.find_element(By.ID, "password").send_keys("Nicolas")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header").click()
    self.driver.find_element(By.ID, "profile").click()
    self.driver.find_element(By.ID, "logoutLink").click()
    self.driver.save_screenshot(f'{sys._getframe().f_code.co_name}.png') # generates a png file with the name
  
